baseURL = 'https://ippermaculture.github.io/'
languageCode = 'fr-fr'
defaultContentLanguage = 'fr'
title = 'IPPermaculture'
theme = 'beautifulhugo'
sectionPagesMenu = "main"

enableRobotsTXT = false

[Params]
  favicon = "avatar.png"
  logo = "avatar.png"
  organizationName = "IPPermaculture"
  [markup.goldmark.renderer]
  unsafe = true
